#!/usr/bin/env bash
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd $DIR

mkdir -p build/cross
cd build/cross
cmake ../.. -DCROSS_COMPILE=TRUE -DCMAKE_TOOLCHAIN_FILE=$NAO_HOME/build/cross-config.cmake
make -j 6
cd $DIR

mkdir -p build/standard
cd build/standard
cmake ../..
make -j 6
