#ifndef PARALLEL_PARAMS_H
#define PARALLEL_PARAMS_H

#include <math/UnscentedKalmanFilterParams.h>

class ParallelParams : public UnscentedKalmanFilterParams {
  public:
    float BALL_DECAY_RATE;
    
    float PROCESS_SELF_XY, PROCESS_SELF_THETA, PROCESS_SELF_VEL_XY, PROCESS_SELF_VEL_THETA;
    float PROCESS_BALL_XY, PROCESS_BALL_VEL_XY;
    
    float COV_SELF_XY, COV_SELF_THETA, COV_SELF_VEL_XY, COV_SELF_VEL_THETA;
    float COV_BALL_XY, COV_BALL_VEL_XY;

    float ODOM_BASE_COV_X, ODOM_BASE_COV_Y, ODOM_BASE_COV_THETA;
    float ODOM_COV_FACTOR_X, ODOM_COV_FACTOR_Y, ODOM_COV_FACTOR_THETA;

    float 
      MAX_INNOVATION_ODOM, MAX_INNOVATION_SINGLEOBJ, MAX_INNOVATION_MULTIOBJ,
      MAX_INNOVATION_SHORTLINE, MAX_INNOVATION_LONGLINE, 
      MAX_INNOVATION_SEENBALL, MAX_INNOVATION_BALLVEL, MAX_INNOVATION_SHAREDBALL, MAX_INNOVATION_COACHBALL, MAX_INNOVATION_CENTERCIRCLE, MAX_INNOVATION_CENTERLINE, MAX_INNOVATION_INTERSECTION;

    float MODEL_SWITCH_ALPHA_FACTOR;

    float ODOM_FACTOR_XY, ODOM_FACTOR_THETA, GYRO_FACTOR_THETA;
    float ODOM_THETA_WEIGHT, GYRO_THETA_WEIGHT;

    float PROCESS_BUMP_FACTOR, PROCESS_FALLEN_ROBOT_FACTOR, PROCESS_FALLEN_BALL_FACTOR, PROCESS_STANDING_ROBOT_FACTOR, PROCESS_MOVING_BALL_FACTOR;
};

#endif
