#!/usr/bin/env bash
# Installer Preamble #
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $DIR/common.sh
#--------------------#

# Add the experimental toolchain
echo "Begin updates"
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get update

# Install packages
echo "Install packages"
sudo apt-get install -y build-essential ccache libmpfr-dev libdevil-dev libode-dev libnotify-bin git fping doxygen qt4-designer mpg123 python-pip g++-5 libasound2-dev

# Boost
sudo apt-get install -y libboost-system-dev libboost-thread-dev libboost-program-options-dev libboost-serialization-dev libboost-regex-dev libboost-test-dev libboost-filesystem-dev

# Tool dependencies
echo "Install tool dependencies."
sudo add-apt-repository -y ppa:xqms/opencv-nonfree
sudo apt-get update
sudo apt install libopencv-*2.4v5=2.4.9.1+dfsg-1.5ubuntu1xqms2~xenial1
sudo apt install libopencv-core-dev=2.4.9.1+dfsg-1.5ubuntu1xqms2~xenial1
sudo apt install libopencv-flann-dev=2.4.9.1+dfsg-1.5ubuntu1xqms2~xenial1
sudo apt install libopencv-imgproc-dev=2.4.9.1+dfsg-1.5ubuntu1xqms2~xenial1
sudo apt install libopencv-features2d-dev=2.4.9.1+dfsg-1.5ubuntu1xqms2~xenial1
sudo apt install libopencv-nonfree-dev=2.4.9.1+dfsg-1.5ubuntu1xqms2~xenial1
sudo apt install libopencv-gpu-dev=2.4.9.1+dfsg-1.5ubuntu1xqms2~xenial1
sudo apt install libopencv-ml-dev=2.4.9.1+dfsg-1.5ubuntu1xqms2~xenial1
sudo apt install libopencv-highgui-dev=2.4.9.1+dfsg-1.5ubuntu1xqms2~xenial1
sudo apt install libopencv-video-dev=2.4.9.1+dfsg-1.5ubuntu1xqms2~xenial1
sudo apt install libopencv-objdetect-dev=2.4.9.1+dfsg-1.5ubuntu1xqms2~xenial1
sudo apt install libopencv-ts-dev=2.4.9.1+dfsg-1.5ubuntu1xqms2~xenial1
sudo apt install libopencv-calib3d-dev=2.4.9.1+dfsg-1.5ubuntu1xqms2~xenial1
sudo apt install libopencv-legacy-dev=2.4.9.1+dfsg-1.5ubuntu1xqms2~xenial1
sudo apt install libopencv-stitching-dev=2.4.9.1+dfsg-1.5ubuntu1xqms2~xenial1
sudo apt install libopencv-contrib-dev=2.4.9.1+dfsg-1.5ubuntu1xqms2~xenial1
sudo apt install libopencv-ocl-dev=2.4.9.1+dfsg-1.5ubuntu1xqms2~xenial1
sudo apt install libopencv-superres-dev=2.4.9.1+dfsg-1.5ubuntu1xqms2~xenial1
sudo apt-get install -y libbz2-dev libfftw3-dev freeglut3-dev libqglviewer-dev-qt4 libqwt-dev libqt4-dev libqtcore4 libqt4-opengl-dev libpython2.7-dev
# libopencv-nonfree-dev : Depends: libopencv-features2d-dev (= 2.4.9.1+dfsg-1.5ubuntu1xqms2~xenial1) but 2.4.9.1+dfsg-1.5ubuntu1.1 is to be installed
#                          Depends: libopencv-nonfree2.4v5 (= 2.4.9.1+dfsg-1.5ubuntu1xqms2~xenial1) but it is not going to be installed


# Latest cmake
wget -N $NAO_LIBS/cmake-data_3.5.1-1ubuntu3_all.deb
sudo dpkg -i cmake-data_*
wget -N $NAO_LIBS/cmake_3.5.1-1ubuntu3_amd64.deb
sudo dpkg -i cmake_*

# Install libpng
wget -N $NAO_LIBS/libpng-1.5.23.tar.gz
tar zxvf libpng-1.5.23.tar.gz
cd libpng-*
cmake .
make
sudo mv libpng15.so* /usr/lib/x86_64-linux-gnu/
cd ..

libs=( alglib yaml-cpp flatbuffers )
for lib in "${libs[@]}"
do
  rm -rf $NAO_HOME/lib/$lib
  wget -N $NAO_LIBS/$lib.tar.gz
  tar zxvf $lib.tar.gz
  mv $lib $NAO_HOME/lib/
done

set +e
sudo apt-get remove swig* -y # This will fail if we install using the method below
sudo apt install -y libpcre3 libpcre3-dev  # needed to install swig
set -e
wget $NAO_LIBS/swig-3.0.8.tar.gz
tar zxvf swig-3.0.8.tar.gz
cd swig-*
./configure --host=i686-sbr-linux --build=x86_64-pc-linux-gnu
make -j8
sudo make install
sudo ln -sf /usr/local/bin/swig /usr/local/bin/swig3.0

cd $NAO_HOME/lib/flatbuffers
mkdir -p build
cd build
cmake ..
make
sudo make install

wget $NAO_LIBS/vim.tar.gz

cd $NAO_HOME/lib/yuview
./compile
