#!/usr/bin/env bash

# Installer Preamble #
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $DIR/common.sh
#--------------------#

sudo apt install gcc-multilib g++-multilib lib32z1


wget -N $NAO_LIBS/kernel_driver.tar.gz
mkdir -p $NAO_HOME/install/linux_aldebaran
tar zxvf kernel_driver.tar.gz -C $NAO_HOME/install/linux_aldebaran


mkdir -p $NAO_HOME/install/robot_libs

wget -N $NAO_LIBS/beignet.tar.gz
wget -N $NAO_LIBS/opencl_required_libs.tar.gz

cd $NAO_HOME/install/robot_libs
tar -xvf ../opencl_required_libs.tar.gz 
tar -xvf ../beignet.tar.gz

cd $NAO_HOME/lib/detect_lib/
bash setup.sh
