set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER x86_64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER x86_64-linux-gnu-g++)

set(CMAKE_SYSROOT "$ENV{NAO_HOME}/tools/NaoImage/root")

set(CMAKE_CXX_FLAGS "-march=silvermont")
set(CMAKE_C_FLAGS "-march=silvermont")

set(CMAKE_FIND_ROOT_PATH "$ENV{NAO_HOME}/build/install_cross")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(PYTHON_SOABI cpython-38-x86_64-linux-gnu)

set(THREADS_PTHREAD_ARG "0"
	CACHE STRING "Result from TRY_RUN" FORCE)
